// Eren'in raporda paylaştığı, izin verilen referans firmalar.
// Görsel logoları sonradan Sanity üzerinden yüklenecek; bu liste fallback.

export type ReferenceCompany = {
  name: string;
  sector?: string;
  featured?: boolean;
};

export const referenceCompanies: ReferenceCompany[] = [
  { name: "Arçelik", featured: true, sector: "Beyaz Eşya" },
  { name: "Şişecam (Cam Elyaf Sanayii A.Ş.)", featured: true, sector: "Cam ve Kimya" },
  { name: "Hayat Kimya", featured: true, sector: "Kimya" },
  { name: "Roketsan", featured: true, sector: "Savunma" },
  { name: "Eczacıbaşı", featured: true, sector: "Sağlık ve Tüketim" },
  { name: "Toyota Tsusho", featured: true, sector: "Otomotiv" },
  { name: "Mars Lojistik", featured: true, sector: "Lojistik" },
  { name: "THY", featured: true, sector: "Havacılık" },
  { name: "Arkas Lojistik", sector: "Lojistik" },
  { name: "Tosçelik", sector: "Demir Çelik" },
  { name: "Tat Gıda", sector: "Gıda" },
  { name: "Aksa Akrilik", sector: "Kimya" },
  { name: "Asaş Alüminyum", sector: "Metal" },
  { name: "Fırat Plastik", sector: "Plastik" },
  { name: "Hayat Kimya", sector: "Kimya" },
  { name: "Adopen", sector: "Yapı" },
  { name: "Kalekim", sector: "Yapı" },
  { name: "Kervan", sector: "Gıda" },
  { name: "Sirma", sector: "İçecek" },
  { name: "ABC Deterjan", sector: "Temizlik" },
  { name: "ABS Alçı", sector: "Yapı" },
  { name: "C Steinweg Levant", sector: "Lojistik" },
  { name: "Chryso Kat Katkı Malz.", sector: "Yapı Kimyasalları" },
  { name: "Cronimet", sector: "Metal" },
  { name: "Çobanpınar", sector: "Gıda" },
  { name: "Deva Holding A.Ş.", sector: "İlaç" },
  { name: "Docotton Group", sector: "Tekstil" },
  { name: "EAE", sector: "Elektrik" },
  { name: "Ege Kimya", sector: "Kimya" },
  { name: "Enpay", sector: "Enerji" },
  { name: "Erşen Antrepo", sector: "Lojistik" },
  { name: "Frimpeks", sector: "Etiket/Baskı" },
  { name: "Günöz Tekstil", sector: "Tekstil" },
  { name: "Hasçelik Kablo", sector: "Kablo" },
  { name: "Horoz Lojistik", sector: "Lojistik" },
  { name: "HSA Enerji", sector: "Enerji" },
  { name: "İNKA", sector: "Yapı" },
  { name: "İskefe Holding", sector: "Holding" },
  { name: "Kartonsan", sector: "Karton" },
  { name: "Kırmızıgül Kozmetik", sector: "Kozmetik" },
  { name: "Kronospan", sector: "Mobilya/Levha" },
  { name: "Makbul", sector: "Gıda" },
  { name: "Mondi", sector: "Ambalaj" },
  { name: "Ode Yalıtım", sector: "Yapı" },
  { name: "Özdilek", sector: "Perakende/Tekstil" },
  { name: "Özismak", sector: "Makina" },
  { name: "Parex", sector: "Yapı Kimyasalları" },
  { name: "Patiswiss", sector: "Gıda/Çikolata" },
  { name: "Polinas", sector: "Ambalaj" },
  { name: "Poliport Kimya", sector: "Kimya/Liman" },
  { name: "Qua Granite", sector: "Seramik" },
  { name: "Rebul Kozmetik", sector: "Kozmetik" },
  { name: "Reis Makina", sector: "Makina" },
  { name: "Sarten Ambalaj", sector: "Ambalaj" },
  { name: "Silkcoat", sector: "Boya" },
  { name: "Sistem Alüminyum", sector: "Metal" },
  { name: "Sörmaş", sector: "Refrakter" },
  { name: "Targid Tarım", sector: "Tarım" },
  { name: "Tarım Kredi", sector: "Tarım Kooperatif" },
  { name: "Tedi", sector: "Perakende" },
  { name: "Teka", sector: "Beyaz Eşya" },
  { name: "Vatan Kablo", sector: "Kablo" },
  { name: "Vatan Plastik", sector: "Plastik" },
  { name: "Yataş", sector: "Mobilya" },
  { name: "Yörpaş", sector: "Gıda" },
];

export const totalProjectsApprox = "Yüzlerce proje";
